### ISSUE TITLE
Local development

### ISSUE THREAD

**Issue by llermaly** [googleworkspace/gws-genai-addon-sample#21]
Hi @Mansari and @vinay-google  

Thanks for this great example! , was very useful. 

I have everything working but now I'm not sure how my team and I can work locally on the project.

What I did was to tunnel `server.js` with ngrok and put the public url on `deployment.json` and `default.json`, then rebuilding . It works, I can see my local changes but now if anyone wants to work it will have to re-deploy with their own ngrok url blocking the rest of the team. 

Is there another way to work locally?  I could only find this which shows there is live reload: https://developers.googleblog.com/2021/03/evolving-google-workspace-add-ons-with.html but it doesnt explain how

Thanks!

**Comment by Mansari** [comment]
Hi @llermaly,

Thank you for your feedback! I love what you shared about building a local test environment, that would be a great blog post to publish if you are interested, or feel free to add it as an addition to the READ.ME.

Now for co-developing an add-on in a team, there are a few ways I can think of setting this up:

## Option 1 : One add-on that everyone works on it

In this case, you will deploy ONE copy of the add-on, [publish it internally your domain](https://developers.google.com/workspace/marketplace/how-to-publish), and then either install it for everyone as an admin (using admin install) or have those developing install it from the [Google Workspace Marketplace](https://workspace.google.com/marketplace).

This copy of the add-on will be pointing to a published HTTPS endpoint that the team controls (e.g. linked to a dev/staging copy of the add-on backend code), and as the team continues to push their updates to this branch/codebase, you either manually update the deployment or have a CI/CD pipeline that does that. You can configure a CI/CD (or a deployment script) to pick any differences in the `deployment.json` for example, and use the [Google Workspace Add-ons APIs] (https://developers.google.com/workspace/add-ons/reference/rest) to create/update deployments, and refresh your hosting server with the latest checked-in backend code. Everyone will now see the latest version of the add-on and will be able to collaborate / QA one version.

## Option 2 : Every developer has their own copy of the add-on

In this case, everyone will do exactly what you did. They will have their own add-on that is linked to their local codebase and any refresh will show up in their own version.

There is nothing that prevents you from doing both. You can have an individual copy of the add-on for each developer linked to their local code, and you can have one (or many) shared copies - staging, QA, prod, that are shared amongst the team members.

These ideas are just off the top of my head before I head to sleep, so forgive me if I missed anything, and feel free to comment if you have any additional questions.

**Comment by llermaly** [comment]
Thanks for your quick answer! . Option 1 will not allow live testing, right?

**Comment by Mansari** [comment]
It all depends on where the code is running - if you point this version of the add-on to the code running on your machine, then you can debug it live on yours. If you change the endpoints to point to someone else's machine, then it can be debug there.

You can indeed run Cloud Run (which is used in this sample) [locally](https://cloud.google.com/run/docs/testing/local) . If you wanted to refactor the code/deployment to use Cloud Functions instead, they can also be run [locally](https://cloud.google.com/functions/docs/running/overview).

Does this help? If you can let me know how you plan to setup the dev environment for your team, or what is your ideal setup for debugging/testing, I am sure @vinay-google may have some more guidance to share as well.

**Comment by llermaly** [comment]
@Mansari Maybe I'm missing something, because to run it locally what I did was to tunnel localhost to a public address that I had to add to the config, then to test the UI I went to the actual addon. 

Doing this if another member wants to work and do the same , will override the URL I created and I will not be able to work on my changes.

Is this accurate? Or there is a way to set the URL to localhost and see live changes in the UI without affecting others ? 

If we use Cloud Run locally we should only replace the URL in the json config? or tunneling is also needed to be reachable from the addon? 

Sorry for so many questions, I'm not very familiar to this workflow. On similar situations (e.g: atlassian apps) the repo comes with a way to run the server locally and set the app to developer mode.

**Comment by Mansari** [comment]
@llermaly You are correct. If each member wants to test on their local machine, then they would have to do the tunneling + updating the deployment manifest to point to their URL, thus overriding the other's changes.

if you are looking for a collaborative coding environment where everyone have access to the same codebase and the add-on is linked to that codebase, I would then suggest using something like [Repl.it](https://replit.com/site/multiplayer) (not an endorsement as I have not personally used it) or similar shared IDE / hosted code solutions may be the answer. In that setup, you can host one endpoint that you can point the add-on to, but you + your colleagues will have access to the code that runs it to monitor/modify it together.

Does that help? I asked my colleague @PierrickVoulet who also might be able to add more thoughts on this.

**Comment by Mansari** [comment]
@llermaly BTW a new guide on how to [debug Google Workspace Add-ons](https://developers.google.com/workspace/add-ons/guides/debug) has just been published. It features a similar approach using `ngrok`, but might be helpful to review if it gives you any additional guidance.

**Comment by Mansari** [comment]
Thanks @llermaly ! Don't hesitate to reach out if anything else comes up. For now, I'll mark this issue as resolved.
