### ISSUE TITLE
render_actions vs renderActions ?

### ISSUE THREAD

**Issue by llermaly** [googleworkspace/gws-genai-addon-sample#22]
I just noticed you mention `renderActions` in the common card ui generator, and then `render_actions` in the card ui generators, what's the difference? 

What I want to achieve is to create a dynamic dropdown (fetch from a database and based on the selection display a list of items).

The problem is I can't get the `onChangeAction` to work this is on my home card so I configured the action to trigger the function of my home card.

```
              {
                widgets: [
                  {
                    selectionInput: {
                      type: 'DROPDOWN',
                      name: 'projects',
                      label: 'Select project',
                      items: projects.map((project) => ({
                        text: project.name,
                        value: project.id,
                        selected: project.id === selectedProjectId,
                      })),
                      onChangeAction: {
                        function:
                          'https://xxxxxxxx/onCalendarHomePageOpen',
                        parameters: [],
                      },
                    },
                  },
                ],
              }
```

I see this error: 

> Cannot find field: action in message google.apps.card.v1.SubmitFormResponse

Then I add render_actions and the onChange works, but the rest state breaks. 

This same thing happens when I try to navigate back to the home card from another one.

Tried with `updateCard` instead of `pushCard` but no luck.

Thank you very much

**Comment by llermaly** [comment]
I could find more information here: 

https://codelabs.developers.google.com/codelabs/workspace-add-on-nodejs-cloudrun#5


I hope this is useful for someone else. Still not sure whats the difference between `render_actions` and renderActions, and when to use renderActions at all.

**Comment by Mansari** [comment]
I do not think this was intentional @PierrickVoulet . If they are treated the same, we should pick one of them which seems to be `renderActions` based on our [alternative runtimes docs](https://developers.google.com/workspace/add-ons/guides/alternate-runtimes).

I will test and create a PR to update the code. Thanks for flagging @llermaly and @PierrickVoulet
